package com.resolve.qa.framework.common;

public enum COMPARE_METHOD_TYPE
{
    EQUAL, NOEQUAL, LESS, LESSOREQUAL, GREATER, GREATEROREQUAL, CONTAIN, NOCONTAIN, INCREASEEQUAL, NOTEMPTY, ISEMPLTY, SIZEEQUAL
}
